name: CodeGuru Reviewer
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CodeGuru Reviewer
        uses: aws-actions/codeguru-reviewer@v1.1